package com.mannanlive.settlers.core.model.game;

public enum GameStage {
    SETUP, SETUP_FIRST_SETTLEMENT, SETUP_FIRST_ROAD, SETUP_SECOND_SETTLEMENT, SETUP_SECOND_ROAD,
    PLACE_ROBBER, STEAL_RESOURCE, DISCARD_EXCESS_RESOURCES,
    ROLL, BUILD_ROAD, BUILD_SETTLEMENT, BUILD
}
